# NumPy Tutorial #

An experimentation with NumPy following the tutorial at: https://www.youtube.com/watch?v=8Y0qQEh7dJg

## NumPy Arrays : Creating Arrays

In [2]:
import numpy as np
import matplotlib.pylab as plt
from numpy import random

list_1 = [1,2,3,4,5]
np_arr_1 = np.array(list_1, dtype=np.int8)
print(np_arr_1)

m_list_1 = [[1,2,3],[4,5,6],[7,8,9]]
np_m_arr_1 = np.array(m_list_1)
print(np_m_arr_1)

print(np.arange(1,10))
print(np.linspace(0,5,7))
print(np.zeros(4))
print(np.ones((2,3)))

print(np_m_arr_1.size)
np_arr_2 = np.array([1,2,3,4,5,6])
print(np_arr_2.dtype)

np.random.randint(10,50,5)
np.random.randint(10,50,size=(2,3))

# If you ever want more information about a function, type it followed by ? and then ctrl-enter (to execute).
np.random.randint?

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[0.         0.83333333 1.66666667 2.5        3.33333333 4.16666667
 5.        ]
[0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
9
int32


Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Outp

# Slicing & Indexes

In [3]:
#np_m_arr_1[0,0] = 2

#np_m_arr_1.itemset((0,1),1)

np_m_arr_1.shape

np.take(np_m_arr_1, [0,3,6])
np.put(np_m_arr_1, [0,3,6], [10,10,10])
print(np_m_arr_1)

# Slicing
print(np_arr_1)
print(np_arr_1[:5:2])

#2nd value form each row
print(np_m_arr_1[:,1])
# Flip Array
print(np_m_arr_1[::-1])

#Grab only evens
evens = np_m_arr_1[np_m_arr_1%2==0]
print(evens)

#Grab greater than 5
print(np_m_arr_1[np_m_arr_1>5])

# Other conditionals
print(np_m_arr_1[(np_m_arr_1>5) & (np_m_arr_1<9)])
print(np_m_arr_1[(np_m_arr_1<5) | (np_m_arr_1==10)])
print(np.unique(np_m_arr_1))


[[10  2  3]
 [10  5  6]
 [10  8  9]]
[1 2 3 4 5]
[1 3 5]
[2 5 8]
[[10  8  9]
 [10  5  6]
 [10  2  3]]
[10  2 10  6 10  8]
[10 10  6 10  8  9]
[6 8]
[10  2  3 10 10]
[ 2  3  5  6  8  9 10]


## Reshaping Arrays

In [4]:
print(np_m_arr_1.reshape((1,9)))
print(np.resize(np_m_arr_1, (2,5)))

print("Transposed:")
print( np_m_arr_1.transpose())

print("Swap Axes:")
print(np_m_arr_1.swapaxes(0,1))

print("Flatten (Row Order)")
print(np_m_arr_1.flatten())

print("Flatten (Column Order)")
print(np_m_arr_1.flatten('F'))

print("Sorted Rows")
np_m_arr_1.sort(axis=1)
print(np_m_arr_1)

print("Sorted Columns")
np_m_arr_1.sort(axis=0)
print(np_m_arr_1)

[[10  2  3 10  5  6 10  8  9]]
[[10  2  3 10  5]
 [ 6 10  8  9 10]]
Transposed:
[[10 10 10]
 [ 2  5  8]
 [ 3  6  9]]
Swap Axes:
[[10 10 10]
 [ 2  5  8]
 [ 3  6  9]]
Flatten (Row Order)
[10  2  3 10  5  6 10  8  9]
Flatten (Column Order)
[10 10 10  2  5  8  3  6  9]
Sorted Rows
[[ 2  3 10]
 [ 5  6 10]
 [ 8  9 10]]
Sorted Columns
[[ 2  3 10]
 [ 5  6 10]
 [ 8  9 10]]


## Stacking and Splitting

In [18]:
ss_arr_1 = np.random.randint(10, size =(2,2))
print("ss_arr_1\n",ss_arr_1)

print()

ss_arr_2 = np.random.randint(10, size =(2,2))
print("ss_arr_1\n",ss_arr_2 )

# Stack 2 under 1
print("Vertical Stack")
print(np.vstack((ss_arr_1, ss_arr_2)))


print("Horizontal Stack")
print(np.hstack((ss_arr_1, ss_arr_2)))

print()

ss_arr_3 = np.delete(ss_arr_1, 1, 0)
ss_arr_4 = np.delete(ss_arr_2, 1, 0)
print("Column Stack\n", np.column_stack((ss_arr_3, ss_arr_4)))
print("Row Stack\n", np.row_stack((ss_arr_3, ss_arr_4)))

ss_arr_5 = np.random.randint(10, size =(2,10))
print("ss_arr_5\n", ss_arr_5)


print("Split to 5 equal arrays\n", np.hsplit(ss_arr_5, 5))

print("Split to 2nd, 4th, and Rest \n", np.hsplit(ss_arr_5, (2,4)))

ss_arr_1
 [[0 2]
 [6 1]]

ss_arr_1
 [[6 4]
 [4 6]]
Vertical Stack
[[0 2]
 [6 1]
 [6 4]
 [4 6]]
Horizontal Stack
[[0 2 6 4]
 [6 1 4 6]]

Column Stack
 [[0 2 6 4]]
Row Stack
 [[0 2]
 [6 4]]
ss_arr_5
 [[8 3 2 6 0 1 3 9 1 1]
 [9 1 7 8 3 2 9 7 8 8]]
Split to 5 equal arrays
 [array([[8, 3],
       [9, 1]]), array([[2, 6],
       [7, 8]]), array([[0, 1],
       [3, 2]]), array([[3, 9],
       [9, 7]]), array([[1, 1],
       [8, 8]])]
Split to 2nd, 4th, and Rest 
 [array([[8, 3],
       [9, 1]]), array([[2, 6],
       [7, 8]]), array([[0, 1, 3, 9, 1, 1],
       [3, 2, 9, 7, 8, 8]])]


## Copying

In [23]:
cp_arr_1 = np.random.randint(10, size =(2,2))

cp_arr_2 = cp_arr_1

print("cp_arr_1\n", cp_arr_1)
print("cp_arr_2\n", cp_arr_2)

cp_arr_2[0,0] = 11
print("After changing array 2, which is not a real copy of array 1")
print("cp_arr_1\n", cp_arr_1)
print("cp_arr_2\n", cp_arr_2)

cp_arr_3 = cp_arr_1.view()
cp_arr_3 = cp_arr_3.flatten('F')
print("After flattening array 3, which is not a view of array 1")
print("cp_arr_1\n", cp_arr_1)
print("cp_arr_3\n", cp_arr_3)

cp_arr_1[0,1]=12
print("After changing array 1, with array 3 as a view, view does make a copy")
print("cp_arr_1\n", cp_arr_1)
print("cp_arr_3\n", cp_arr_3)

cp_arr_4 = cp_arr_1.copy()

cp_arr_1
 [[0 9]
 [3 9]]
cp_arr_2
 [[0 9]
 [3 9]]
After changing array 2, which is not a real copy of array 1
cp_arr_1
 [[11  9]
 [ 3  9]]
cp_arr_2
 [[11  9]
 [ 3  9]]
After flattening array 3, which is not a view of array 1
cp_arr_1
 [[11  9]
 [ 3  9]]
cp_arr_3
 [11  3  9  9]
After changing array 1, with array 3 as a view
cp_arr_1
 [[11 12]
 [ 3  9]]
cp_arr_3
 [11  3  9  9]


## Basic Math

In [38]:
arr_3 = np.array([1,2,3,4])
arr_4 = np.array([2,4,6,8])

print("Add\n", arr_3 + arr_4)
print("Subtract\n", arr_3 - arr_4)
print("Multiply\n", arr_3 * arr_4)
print("Divide\n", arr_3 / arr_4)

arr_5 = np.random.randint(100, size=(4))
print("arr_5\n", arr_5)
arr_6 = np.random.randint(100, size=(2,3))
print("arr_6\n", arr_6)

arr_f = random.rand(4)
print("rand_f\n", arr_f)

print("random choice\n", random.choice(arr_f))

print("Sum of arr_3\n", arr_3.sum())
print("Sum of columns in arr_6\n", arr_6.sum(axis=0))
print("Sum of rows in arr_6\n", arr_6.sum(axis=1))

print("Minimum of columns in arr_6\n", arr_6.min(axis=0))
print("Maximum of rows in arr_6\n", arr_6.max(axis=1))

print("arr_3 added to 5\n", np.add(arr_3, 5))

#np.sqrt
#np.power
#np.exp
#np.log
#np.log2
#np.lcm
#np.gcd
#np.floor
#np.ceiling
# Index of maximum
arr_7 = np.random.randint(100, size=(5,3))
print("arr_7\n", arr_7)
mc_index = arr_7.argmax(axis=0)
print(mc_index)

Add
 [ 3  6  9 12]
Subtract
 [-1 -2 -3 -4]
Multiply
 [ 2  8 18 32]
Divide
 [0.5 0.5 0.5 0.5]
arr_5
 [63 61 38 15]
arr_6
 [[13 10 97]
 [70 39 60]]
rand_f
 [0.43774207 0.76918603 0.21237127 0.31855884]
random choice
 0.2123712687062722
Sum of arr_3
 10
Sum of columns in arr_6
 [ 83  49 157]
Sum of rows in arr_6
 [120 169]
Minimum of columns in arr_6
 [13 10 60]
Maximum of rows in arr_6
 [97 70]
arr_3 added to 5
 [6 7 8 9]
arr_7
 [[76  2  7]
 [19 56 45]
 [94 77 43]
 [41 45  6]
 [30 16 90]]
[2 2 4]


## Reading from Files ##

## Linear Algebra Functions